Use wgLogos['wordmark'] for sourcing stratchwiki logo
InternationalScratchWiki/ScratchWikiSkin2 pull request #78
Opened 2021-01-04 16:35 UTC by jdlrobson

This allows other 3rd parties the ability to assign a logo
as well as giving an easier way to control
the logo in the header for sysadmins.

2021-01-04 18:29 UTC, Kenny2github commented
@jacob-g I can't test this because my instance is still on 1.34, can you review and ensure everything looks identical when using this?

2021-01-04 18:33 UTC, jacob-g requested changes
CSS will need to be applied to the logo to preserve the size. We currently get this:
![image](https://user-images.githubusercontent.com/1960707/103567248-13868080-4e89-11eb-9587-e100ca7c6656.png)

2021-01-04 20:28 UTC, jdlrobson commented
mm weird.. I'll take another look to see what's happening here.

2021-01-05 19:00 UTC, jdlrobson commented
Ok! new patch up.

What is the "resources/main.css" file? Is it a duplicate of resources/css/main.css ? Does it serve any purpose?

2021-01-25 02:00 UTC, jacob-g approved these changes

2021-01-25 02:00 UTC, merged